#pragma once
#include <vector>
#include <unordered_map>
#include <memory>
#include <string>
#include <functional>
#include <stdexcept>
#include <utility>
#include <mutex>
#include <variant>
#include <lua.hpp>
#include <windows.h>
#include <CommCtrl.h>
#include <commdlg.h>
#include <shlobj.h>
#include <format>
#include "globalhelpers.h"
#include "windowsfuncs.h"